name: try18_ios_design
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

flutter:
  assets:
    - assets/bug.png
    - assets/check-2.png
    - assets/comments.png
    - assets/comments-2.png
    - assets/file.png
    - assets/git.png
    - assets/plus.png
    - assets/search.png
    - assets/up.png
    - assets/reviewer1.jpeg
    - assets/reviewer4.jpg

  fonts:
    - family: .SF UI Text
      fonts:
        - asset: assets/SFText-Regular.otf
        - asset: assets/SFText-Light.otf
          weight: 300
        - asset: assets/SFText-Medium.otf
          weight: 500
        - asset: assets/SFText-Semibold.otf
          weight: 600
        - asset: assets/SFText-Bold.otf
          weight: 700
  uses-material-design: true