name: t44_large_nav_bar_with_ios_design_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/bug.png
    - assets/check-2.png
    - assets/comments.png
    - assets/comments-2.png
    - assets/file.png
    - assets/git.png
    - assets/plus.png
    - assets/search.png
    - assets/up.png
    - assets/reviewer1.jpeg
    - assets/reviewer4.jpg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
