name: t95_ios_settings_page
description: A new Flutter project.

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  ios_settings_icons:
    git:
      url: https://github.com/xster/flutter-test.git
      path: t96_ios_settings_assets

dev_dependencies:
  flutter_test:
    sdk: flutter
