name: ios_settings_icons

description: Icons from iOS 11's settings app for demonstration purposes.
author: Xiao Yu <xiao@xster.net>
homepage: https://github.com/xster/flutter_test/t96_ios_settings_assets
version: 0.0.1


flutter:
  assets:
   - assets/airplane.png
   - assets/wifi.png
   - assets/bluetooth.png
   - assets/cellular.png
   - assets/hotspot.png
   - assets/vpn.png
   - assets/notifications.png
   - assets/control_center.png
   - assets/disturb.png
   - assets/general.png
   - assets/display.png
   - assets/wallpaper.png
   - assets/sounds.png
   - assets/siri.png
   - assets/face_id.png
   - assets/sos.png
   - assets/battery.png
   - assets/privacy.png
   - assets/itunes.png
   - assets/wallet.png
   - assets/accounts.png
   - assets/contacts.png
   - assets/calendar.png
